version: '3.8'

services:
  postgres:
    image: postgres:14.3
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - postgres
    volumes:
      - ./:/docker_transcendance
    networks:
      - api

volumes:
  pgdata:
    external: false

networks :
  api:
    name : api